<?php
declare(strict_types=1);

namespace frontend\controllers;

use yii\web\Controller;

class PageController extends Controller
{
    public function beforeAction($action)
    {
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    public function actionIndex(string $uuid)
    {
        var_dump($uuid);
    }

}