### Send GET request to JSON-RPC
GET http://rpc-server.loc/rpc
Content-Type: application/json

{
  "id": 999,
  "value": "content"
}

### Send POST request to JSON-RPC Author
POST http://rpc-server.loc/rpc
Content-Type: application/json

{
  "jsonrpc": "2.0",
  "id": 15,
  "method": "getAuthorForm",
  "params": {
    "pageUid": "7cf33c10-705c-4be7-b0cc-05cae535e39c"
  }
}

### Send POST request to JSON-RPC Book
POST http://rpc-server.loc/rpc
Content-Type: application/json

{
  "jsonrpc": "2.0",
  "id": 15,
  "method": "getBookForm",
  "params": {
    "pageUid": "f3ddb723-999c-415b-a5e0-6b913e47bde8"
  }
}
