### Send GET request to JSON-RPC
GET http://rpc-server.loc/rpc
Content-Type: application/json

{
  "id": 999,
  "value": "content"
}

### Send POST request to JSON-RPC Author
POST http://rpc-server.loc/rpc
Content-Type: application/json

{
  "jsonrpc": "2.0",
  "id": 15,
  "method": "getAuthorForm",
  "params": {
    "pageUid": null
  }
}

### Send POST request to JSON-RPC Book
POST http://rpc-server.loc/rpc
Content-Type: application/json

{
  "jsonrpc": "2.0",
  "id": 15,
  "method": "getBookForm",
  "params": {
    "pageUid": null
  }
}
